default:

  #
  # Basic
  #
  server:
    port: 8000

  #
  # Microservice
  #
  microservice:
    basePath: services
    server:
      name: starter/v1

  #
  # Zookeeper
  #
  zookeeper:
    connectionString: localhost:2181
    retry:
      wait: 1000
      count: 3
